/** @format */

import { createAppKit } from "@reown/appkit/react";
import { SolanaAdapter } from "@reown/appkit-adapter-solana/react";
import { solana, solanaTestnet, solanaDevnet } from "@reown/appkit/networks";
import {
  PhantomWalletAdapter,
  SolflareWalletAdapter,
} from "@solana/wallet-adapter-wallets";

// Initialize AppKit configuration
export const initializeAppKit = () => {
  const solanaWeb3JsAdapter = new SolanaAdapter({
    wallets: [new PhantomWalletAdapter(), new SolflareWalletAdapter()],
  });

  const metadata = {
    name: "Reality Check",
    description: "Generated by create next app",
    url:
      typeof window !== "undefined"
        ? window.location.origin
        : "http://localhost:3000/",
    icons: ["https://avatars.githubusercontent.com/u/179229932"],
  };

  createAppKit({
    adapters: [solanaWeb3JsAdapter],
    networks: [solana, solanaTestnet, solanaDevnet],
    metadata,
    projectId: process.env.NEXT_PUBLIC_REOWN_PROJECT_ID ?? "YOUR_PROJECT_ID",
    features: {
      analytics: true,
    },
  });
};
